### PR TITLE
fix: Don't crash when attempting to download local tracks by skipping them

### LINKED ISSUE #84: Playlists with Local Tracks (i.e., no Id) crash app
**Describe the bug**
As the title says. Songs that are added to a playlist but aren't actually known to Spotify's library, and therefore have no Id, crash the application.

**To Reproduce**
Add local tracks to your playlist.

**Expected behavior**
Probably just skipping the track and reporting "a local track was skipped".

image

Line 819 is here, specifically the `track_id: val.id.unwrap(),`:
```rust
impl From<aspotify::Track> for Download {
	fn from(val: aspotify::Track) -> Self {
		Download {
			id: 0,
			track_id: val.id.unwrap(),
			title: val.name,
			subtitle: val
				.artists
				.first()
				.map(|a| a.name.to_owned())
				.unwrap_or_default(),
			state: DownloadState::None,
		}
	}
}
```

**Desktop (please complete the following information):**

- OS: Windows 11, running in Debug mode from source, using a premium account.

### PR DESCRIPTION
**Pull request by 0xNF**
Tracks with no id will crash the application (#84).

This PR fixes this by making the Download of a track with is_local or a None id into an error download. This causes DownOnSpot to correctly report the error, skip over the track, and continue without crashing.

This fix is a modification of the edit suggested by @Daprussiaduck

Closes #84

### CODE REVIEW

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
I think instead of causing an error, local tracks should be filtered away. Ideally wherever `from` is used

**Comment by 0xNF** [comment]
I moved the local check into downloader.rs:

```rust
/// Add URL or URI to queue
	pub async fn add_uri(&self, uri: &str) -> Result<(), SpotifyError> {
		let uri = Spotify::parse_uri(uri)?;
		let item = self.spotify.resolve_uri(&uri).await?;
		match item {
			SpotifyItem::Track(t) => {
				if t.id.is_some() && !t.is_local {
					self.add_to_queue(t.into()).await;
				}
			}
			SpotifyItem::Album(a) => {
				let tracks = self.spotify.full_album(&a.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}
			SpotifyItem::Playlist(p) => {
				let tracks = self.spotify.full_playlist(&p.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}
			SpotifyItem::Artist(a) => {
				let tracks = self.spotify.full_artist(&a.id).await?;
				let queue: Vec<Download> = tracks
					.into_iter()
					.filter(|t| t.id.is_some() && !t.is_local)
					.map(|t| t.into())
					.collect();
				self.add_to_queue_multiple(queue).await;
			}

			// Unsupported
			SpotifyItem::Other(u) => {
				error!("Unsupported URI: {}", u);
				return Err(SpotifyError::Unavailable);
			}
		};
		Ok(())
	}
```

File: src/downloader.rs [hunk 1]
```diff
@@ -84,20 +84,36 @@ impl Downloader {
...
+				if t.id.is_some() && !t.is_local {
+					self.add_to_queue(t.into()).await;
+				}
+			}
 			SpotifyItem::Album(a) => {
 				let tracks = self.spotify.full_album(&a.id).await?;
-				let queue: Vec<Download> = tracks.into_iter().map(|t| t.into()).collect();
+				let queue: Vec<Download> = tracks
+					.into_iter()
+					.filter(|t| t.id.is_some() && !t.is_local)
```
Comment (oSumAtrIX) [inline src/downloader.rs:96]: Can albums be even local? How about Artist tracks in line 114? I thought you could only create playlists with local songs.

Comment (0xNF) [reply src/downloader.rs:96]: no, probably not. I was just covering my bases, really. I can strip the check there if you'd like.

Comment (oSumAtrIX) [reply src/downloader.rs:96]: Please do so and keep the is_local check only where necessary.

Comment (0xNF) [reply src/downloader.rs]: I removed the checks from the non-track branches. After thinking about it, I decided to ignore the `is_local` check in favor of just checking that the track has an id via `track.id.is_some()`. My thinking is that, is_local implies id.is_none, but id.is_none might not imply is_local, and in all cases no id would be an invalid download.

Comment (oSumAtrIX) [reply src/downloader.rs]: Isn't just checking for is_local enough?

Comment (0xNF) [reply src/downloader.rs]: Your call. I'm fine with just doing the is_local check. Since the code is structured to use Option<String> for the track id, I was leaning more into that, but is_local is probably sufficient. The latest push removes the is_some check and includes only the is_local check.

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
Thanks!
